CREATE DATABASE customer_behavior;
USE customer_behavior;

SELECT * FROM customer;
-- Check duplicate rows

select count(*) from 
(
SELECT *,
ROW_NUMBER() OVER(
PARTITION BY customer_id, 
age , 
gender , 
item_purchased , 
category
) AS row_num
FROM CUSTOMER
) T
WHERE ROW_NUM>1;

-- Q1. What is the total revenue generated by male vs female customer?

SELECT gender ,sum(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount ?
 SELECT customer_id,purchase_amount
 FROM customer
 WHERE discount_applied ='yes'
 AND
 purchase_amount >= 
 ( 
 SELECT AVG(purchase_amount) FROM CUSTOMER);
 
-- Q3. WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATINGS?
SELECT item_purchased,ROUND(AVG(REVIEW_RATING),2) AS 'Average Product Rating'
FROM CUSTOMER 
group by item_purchased 
ORDER BY 'Average Product Rating' DESC 
LIMIT 5;

-- Q4. Compare the avergae Purchase Amounts between standard and Express Shipping.
SELECT shipping_type,ROUND( AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;


-- Q5. Do Subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) AS total_customers,
round(avg(purchase_amount),2) AS avg_spend,
round(SUM(purchase_amount),2) AS total_revenue
FROM CUSTOMER
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND (100 * SUM(CASE 
WHEN discount_applied ='YES' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM CUSTOMER
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- numbers of previous purchases, and slow the count of each segment.

WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE
   WHEN previous_purchases = 1 THEN "NEW"
   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
from customer
)
SELECT customer_segment, count(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products withon each category?

WITH items_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS ITEM_RANK
FROM customer
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM items_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyurs (more than 5 previous purchases) also likely to subscriber?
SELECT subscription_status,
count(customer_id) AS Repeat_buyers
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT age_group,
SUM(purchase_amount) AS TOTAL_REVENUE
FROM customer
GROUP BY age_group;